### ISSUE TITLE
Feature request: dont send message if "result" field is blank

### ISSUE THREAD

**Issue by TargetLocked** [Chuanwise/CustomCommands#1]
Currently, setting the result to '' produces a message with only a prefix.
![image](https://user-images.githubusercontent.com/32962687/110796356-cffa2980-82b2-11eb-84d9-5691a65ddf37.png)
Could we remove this blank message, or add a new option on sending a message or not?

希望在result为空的时候就不要发送提示了，在拿PHAPI结合CC写条件跳转的时候会有一吨空消息很影响观感（

另外有个不知道怎么触发的bug是{player}变量有时候不会被替换，这个我还不很确定是不是我的配置错误所以就不单独发issue了，有其他人遇到的话可以补充一点信息

**Comment by chuanwise** [comment]
收到了，正在打开 IDE。一会儿更新。

**Comment by chuanwise** [comment]
已经在已经发布的 `4.1` 版本中修复了 `{player}` 变量的问题，并设置了若无 `result` 项目则不发送任何消息。
